export default [
  {
    buttonClass: "stake-coin",
    btnBackground:
      "repeating-conic-gradient(rgb(6, 112, 147) 0deg 15deg, white 15deg 35deg)",
    position: "relative",
    transform: "translate(0%,0%)",
    border: "border",
    borderBg: "4px solid rgb(6, 112, 147)",
    buttonBg: "white",
    buttonText: "rgb(6, 112, 147)",
    value: 1,
    id: 1,
    animate: false,
    animatClass: "animate1",
  },
  {
    buttonClass: "stake-coin",
    btnBackground:
      "repeating-conic-gradient(rgb(86, 5, 5) 0deg 15deg, white 15deg 35deg)",
    border: "border",
    borderBg: "4px solid rgb(86, 5, 5)",
    buttonBg: "rgb(86, 5, 5)",
    value: 5,
    id: 2,
    animate: false,
    animatClass: "animate2",
  },
  {
    buttonClass: "stake-coin",
    btnBackground:
      "repeating-conic-gradient(green 0deg 15deg, white 15deg 35deg)",
    border: "border",
    borderBg: "4px solid green",
    buttonBg: "green",
    value: 25,
    id: 3,
    animate: false,
    animatClass: "animate3",
  },
  {
    buttonClass: "stake-coin",
    btnBackground: "repeating-conic-gradient(red 0deg 20deg,white 20deg 40deg)",
    border: "border",
    borderBg: "4px solid red",
    buttonBg: "red",
    value: 50,
    id: 4,
    animate: false,
    animatClass: "animate4",
  },
  {
    buttonClass: "stake-coin",
    border: "border",
    value: 100,
    id: 5,
    animate: false,
    animatClass: "animate5",
  },
  {
    buttonClass: "stake-coin",
    btnBackground:
      "repeating-conic-gradient(rgb(190, 22, 50) 0deg 15deg, white 15deg 35deg)",
    border: "border",
    borderBg: "4px solid rgb(137, 4, 26)",
    buttonBg: "rgb(137, 4, 26)",
    value: 500,
    id: 6,
    animate: false,
    animatClass: "animate6",
  },
];
